---
spring:
  datasource:
    url: "jdbc:h2:mem:mydb;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DEFAULT_NULL_ORDERING=HIGH"
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect

stlmpd:
  geocode-api-url-base: ~

management:
  endpoints:
    web:
      exposure:
        include: "*"
