---
services:
  stlmpd:
    image: stlmpd
    build:
      context: ../
      dockerfile: docker/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=postgres
      - JDBC_DATABASE_URL=jdbc:postgresql://db:5432/test
      - JDBC_DATABASE_USERNAME=postgres
      - JDBC_DATABASE_PASSWORD=postgres
    depends_on:
      - db
  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=test
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
