CREATE TABLE service_call
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    address         VARCHAR(255),
    latitude        VARCHAR(255),
    longitude       VARCHAR(255),
    reason          VARCHAR(255),
    service_call_id VARCHAR(255),
    TIME            VARCHAR(255),
    PRIMARY KEY (id)
)