---
name: ci

on:
  push:
    branches:
      - main
    tags-ignore:
      - "*"
  pull_request:
    branches:
      - main
  workflow_dispatch: { }

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4.2.1
        with:
          distribution: temurin
          java-version: 17
          cache: maven
      - name: build
        run: ./mvnw --show-version --no-transfer-progress --update-snapshots package --file=pom.xml --fail-at-end --batch-mode

      - name: deploy
        if: github.event_name != 'pull_request'
        uses: akhileshns/heroku-deploy@v3.13.15
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: stlmpd
          heroku_email: ${{secrets.HEROKU_EMAIL}}
        env:
          HD_GEOCODE_API_TOKEN: ${{secrets.GEOCODE_API_TOKEN}}
          HD_SPRING_PROFILES_ACTIVE: postgres
